version: '3'
services:
  gateway:
    build: ./nginx
    ports:
      - "8888:80"
    depends_on:
      - admin
      - ui

  ui:
    image: wesjordan/soundbin-frontend:latest
    expose:
      - 80
    depends_on:
      - admin
  
  admin:
    command: gunicorn soundbin_admin.wsgi:application --bind 0.0.0.0:8000 
    image: wesjordan/soundbin-admin:dev
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me
